### ISSUE TITLE
Feature request: Expand to include CDF

### ISSUE THREAD

**Issue by eriktar** [michaeldmoore/michaeldmoore-scatter-panel#10]
Love the scatterplots!  

No good deed goes un-punished.  And the punishment is a feature request.  I could really use a CDF as well.  Seems like your module is quite close to being to produce those.  Any chance you take that challenge?

**Comment by michaeldmoore** [comment]
It all depends - what's a CDF?

ah - 2 minutes with my friend, Google and I found this : Cumulative
Distribution Function (CDF)

From the extra minute of reading one of the links, it appears to be the
integral, as in Y' = sum(Yi) where X' <= Xi

Sounds simple enough, and from the article I just scanned over, it seems to
be better than sex - at least to the author of the article.

If you don't mind though, can you send a sample data set along with how you
think it might look as a CDF?  Maybe as an excel spreadsheet etc.  You do
that, and I'll see about adding it somehow in the Scatter panel.

**Comment by eriktar** [comment]
I took the chance that if you know scatter plots well enough to develop grafana plugins for them, you would know or at least easily find out what they are.  At least better than what I would be able to explain in a sentence or two.  I do like CDF's for comparing stuff, but perhaps not to the degree the other author was liking them. :) 

My example.  Ping to a host, then graph it as a time sequence.  So who of these two clients has the better/worse experience?
![image](https://user-images.githubusercontent.com/5344481/116563553-6b4b6a80-a904-11eb-964e-30156f176168.png)

I'm better with gnuplot than excel for these thing, so this is what I use
gnuplot> plot "ping_example_spaces.csv" u 5:(1.) smooth cnorm title "latency max S200Z34015206","ping_example_spaces.csv" u 6:(1.) smooth cnorm title "latency max S200Z34015208"

Which produces this graph
![image](https://user-images.githubusercontent.com/5344481/116568553-dbf48600-a908-11eb-843f-e7e6530e783c.png)

Example file
[ping_example_spaces.csv](https://github.com/michaeldmoore/michaeldmoore-scatter-panel/files/6399451/ping_example_spaces.csv)

**Comment by michaeldmoore** [comment]
Sorry for not getting back to you on this sooner.  I have no excuse other than getting distracted by the glorious summer we've been having here in Southern France.  It's winter now so I've been working on some enhancements, requested by Scatter users etc.  Now as I'm about to make the official release, I noticed your outstanding request, and sadly - it's not in this upcoming release.

On the other hand, re-reading your replies, it seems this might be something that would be helpful with all sorts of panels.  Have you checked out the Grafana built-in data transformation system?  I see lots of these being added these days so maybe the CDF function is already in there.  If not, I suggest you make the feature request to Grafana itself.

M
