### ISSUE TITLE
Feature Request: Display values at data points when hovering over them

### ISSUE THREAD

**Issue by andrew-mcnaught** [michaeldmoore/michaeldmoore-scatter-panel#11]
Hey, testing out the scatter panel today and it looks good!

I was wondering if it would be possible to display the values that your mouse is hovering over similar to that for graphs?

Thanks,
Andrew

**Comment by michaeldmoore** [comment]
Glad you like it.

This is something I intend to add - it might take a while as I'm busy with
other, more pressing things at the moment.  But watch this space....  :)
