### ISSUE TITLE
Working but not graphing?

### ISSUE THREAD

**Issue by eriktar** [michaeldmoore/michaeldmoore-scatter-panel#12]
I have a dateset which looks like this.  It is the mean rsrp, mean ping and max ping for 1min intervals.  The goal is to correlate radio conditions with latency.
![image](https://user-images.githubusercontent.com/5344481/119986253-e798a280-bfc3-11eb-96c0-5d3fbd579871.png)

When I try and plot it, it seems that the plugin understands the data, since the axes auto scale to sane values.  But the content is not plotted.  Any idea why?
![image](https://user-images.githubusercontent.com/5344481/119986440-1f9fe580-bfc4-11eb-9817-09d6a43d8c1c.png)
![image](https://user-images.githubusercontent.com/5344481/119986578-4cec9380-bfc4-11eb-9885-213f63050bb0.png)

**Comment by michaeldmoore** [comment]
It's not obvious.

If you can, open the dashboard settings and send me the json definition -
I'll try it here and see what the problem is.

It will help if you can send the data too, assuming it's nothing secret -
you can use the panel explore feature and export the data as CSV.
Michael Moore

**Comment by eriktar** [comment]
Data is striped of ID's so its safe
[Ping vs rsrp-data-2021-05-28 15 30 34.csv](https://github.com/michaeldmoore/michaeldmoore-scatter-panel/files/6561116/Ping.vs.rsrp-data-2021-05-28.15.30.34.csv)

The querry contained some ID's so I removed that part of the json.

`{
  "datasource": "fmbb flux",
  "description": "https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/",
  "fieldConfig": {
    "defaults": {},
    "overrides": []
  },
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 12,
    "y": 8
  },
  "id": 23763571993,
  "pluginVersion": "7.5.5",
  "targets": [
    {
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "orderByTime": "ASC",
      "policy": "default",
      "query": "Redacted as it contains customer ID's
"
      "refId": "E",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "title": "Ping vs rsrp",
  "type": "michaeldmoore-scatter-panel",
  "timeFrom": null,
  "timeShift": null,
  "transformations": [],
  "options": {
    "xAxis": {
      "col": 2,
      "inverted": false
    },
    "xAxisExtents": {
      "min": null,
      "max": null
    },
    "xAxisTitle": {
      "text": "RSRP",
      "color": "white",
      "textSize": 1
    },
    "fieldSets": [
      {
        "col": 1,
        "color": "#F2CC0C",
        "dotSize": 2,
        "lineSize": 1,
        "lineType": "none",
        "hidden": false
      }
    ],
    "yAxisExtents": {
      "min": null,
      "max": null
    },
    "yAxisTitle": {
      "text": "latency",
      "color": "#777",
      "textSize": 1
    },
    "rotateYAxisTitle": false,
    "legend": {
      "show": false,
      "size": 3
    },
    "grid": {
      "color": "gray"
    },
    "border": {
      "show": false,
      "color": "yellow",
      "size": 1
    }
  }
}`

**Comment by michaeldmoore** [comment]
Hmmmm...

I admit, this has me stumped for the moment.

I tried importing your dashboard JSON after switching out the datasource
and query etc., and it all seems to be working the way I think it should.

[image: image.png]

I can't say I understand exactly what you're trying to show here, but I
take it as plotting ping_mean (labeled as latency on the Y axis), vs RSRP
on the X axis.

One odd thing though - I usually select table-formatted data for this kind
of thing, as it is much less restrictive regarding the data type, names and
formats.  You might try defining the data as table format (as it is in the
first screen cap, using the table panel visualization).

ANother thing you can try if this still isn't working - open the dev debug
panel in your browser (F12 on most browsers) and see if there are error
messages.  Some error messages are expected, being generated by Grafana's
react plumbing.  Look out for ERRORs though, these might indicate some part
of the code is being cancelled before it gets to draw the actual dots.


Good luck

**Comment by eriktar** [comment]
The image did not come through.  I assume it shows that it's working on your end?

Regarding using table view.  Perhaps it is an important detail that I'm using flux, not influql for this query?  The output formatting box simply is not there when I use flux.  I think I striped out the ID parts from the query and inserted it here.

`
pcc_rsrp_raw = from(bucket:"fmbb/autogen")
 |> range(start: -90m, stop: now())
 |> filter(fn: (r) => r._measurement == "cellular" and
 r._field == "rsrp"  and
 r.serial_number == "REDACTED" and
 r.carrier == "4g" 
 )

pcc_rsrp_mean = pcc_rsrp_raw
 |> window(every: 1m)
 |> mean()


ping_raw = from(bucket:"fmbb/autogen")
 |> range(start: -90m, stop: now())
 |> filter(fn: (r) => r._measurement == "ping"  and
 r._field == "latency"  and
 r.serial_number == "REDACTED" and
 r.server == "REDACTED"
 )

ping_mean = ping_raw
 |> window(every: 1m)
 |> mean()

ping_max = ping_raw
 |> window(every: 1m)
 |> max()


ping_max_mean = join(
  tables: {mean:ping_mean, max:ping_max},
  on: ["_start"]
)


JoinOutput = ["_field","_value","_value_max","_value_mean"]

rsrp_ping = join(
  tables: {rsrp:pcc_rsrp_mean, ping:ping_max_mean},
  on: ["_start"]
 )
 |> keep(columns:JoinOutput)
 |> map(fn:(r) => ({_field: r._field_max,_time: r._time,ping_max: r._value_max,rsrp: -1.0 * r._value,ping_mean: r._value_mean}))
 |> sort(columns:["_value_rsrp"], desc: true)


rsrp_ping 
`

The output format looks like this.  Single table, multiple values.

`
--- 1
result  table  ping_max  ping_mean           rsrp
        0      166.679   43.22923333333333   77
        0      29.064    21.817508474576275  75
        0      93.634    46.52378333333333   76
        0      152.924   50.30365            76
        0      79.644    36.91215517241379   76
        0      30.953    22.171830508474574  76
        0      76.388    45.11674576271187   75
        0      62.906    46.07684745762712   75
        0      81.073    49.83681355932203   76
        0      29.016    20.78038333333333   76
        0      26.712    21.34825            75
        0      65.343    34.400694915254235  75
        0      53.96     25.247933333333336  75
        0      75.323    48.61285            76
        0      64.834    48.108999999999995  76
        0      96.999    35.47245762711864   75
        0      68.343    48.2105             75
        0      77.547    31.531793103448276  76
        0      78.029    44.86931034482759   76
        0      33.329    21.7185593220339    76
        0      95.689    50.021183333333326  76
        0      85.619    49.761183333333335  77
        0      48.677    22.89998333333334   75
        0      35.782    22.671149999999997  76
        0      120.287   35.037400000000005  75
        0      78.544    46.110661016949145  76
`

**Comment by eriktar** [comment]
From a panel which draws the expected scatterplott.  (Different project, different server, different data and using influxql)
![image](https://user-images.githubusercontent.com/5344481/120189096-338f5580-c217-11eb-88bf-b222351a5988.png)

From the graph which I reported this bug.  A bunch of NaN's where I expected coordinates for the plot points
![image](https://user-images.githubusercontent.com/5344481/120189236-5de11300-c217-11eb-8e3a-13818d170b9d.png)

**Comment by michaeldmoore** [comment]
Interesting. This data set does use the table format, unlike the one you
sent earlier - they both should work though, but table format means you can
have more than one data series, also, the field naming is retained.  I got
both formats working though, so that's not THE problem.  All those NaNs
seem to be a clue.  Perhaps this is a field format issue, with the data
being processed as strings rather than numeric values.  Not sure what to do
with this.


Sending the generated SVG is really helpful - what a good idea.  If you
can, can you send the svgs as text though instead of a photograph of the
svg?

From what I see in the first example (the one that works, apparently), you
have lots of identical circles over-laying each other. All on exactly the
same spot.  It doesn't really matter to me, but presumably, this is what
you were expecting.


Here's an idea to play with - can you set the Line property to 'simple'
rather than none?  The result, if it shows anything, will be a meaningless
tangle.  Still, it would show that the x and y coordinates make sense.  I
think they must make sense, as you noted, the auto-scaling of the axis
seems to be working.  Just the routine that generated the svg for each dot
appears to be throwing an error - returning NaN instead of the circle SVG
code.

Very interesting.


The code that draws the dots is this (in ScatterPanel.tsx)
function drawDots(options: ScatterOptions, fieldSets: FieldSet[], xValues:
number[], yValues: number[][], xScale: Function, yScale: Function) {
  return fieldSets.map((y, i: number) => (
    xValues.map((x, j) => {
      if (y.dotSize > 0) {
        let className = 'ScatterSet-' + i
        if (options.legend.size && fieldSets[i].hidden) {
          className += ' ScatterSetHidden'
        }

        return <circle
          key={'circle-[' + y + '][' + i + ']'}
          cx={xScale(x)}
          cy={yScale(yValues[i][j])}
          r={y.dotSize}
          className={className}
          fill={y.color} />
      }
      else
        return null;
    })
  ))
}

It might look complicated if you are not familiar with react and typescript
code, but essentially, this routine takes an array of data points and
outputs an array of svg elements (circles) which get added as a group to
the svg structure.  Somehow, in your case, it returns an array of NaNs
which makes no sense to me.

Maybe, if you feel brave enough, you could open the browser dev window
(F12) and try to set a breakpoint on the code above (it will have been
translated into pure javascript).  It would be interesting to step through
and see what it generates here.

Also, as I think I mentioned earlier - look for error messages in the
browser development console display.  There ought to be a clue as to why it
generates NaN instead of the circle code

**Comment by eriktar** [comment]
The overlapping circles are intentional.  I use them with transparency to highlight hot spots of correlations.  

Line = simple, nothing in the graph.

When I found the NaN's in the SVGs I was looking for the messages in the console log.  And since I'm not well versed in web development I found the SVGs in stead, not really a good idea, just dumb luck. :)  I think I found the console log now.  Nothing alarming there as far as I can see.

`DashboardModel.on is deprecated use events.subscribe DashboardModel.ts:892:12
DashboardModel.off is deprecated DashboardModel.ts:898:12
DashboardModel.on is deprecated use events.subscribe DashboardModel.ts:892:12
Use of drawWindow method from CanvasRenderingContext2D is deprecated. Use tabs.captureTab extensions API instead https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab pagedata-script.js:1:5791
The resource at “https://example.server.com/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. flux-testbed
performance 
Array(3) [ {…}, {…}, {…} ]
PerformanceBackend.ts:39:12
`

Regarding breakpoints and webdev.  I feel brave enough - just not competent enough.  Tried for a few minutes now to figure out how where find the code and set the break points.  No luck.  If you are willing to invest a little time pointing me in the right direction I probably can figure it out.  Normally I just write perl and shell code for embedded devices.  Having a GUI is baffling to me.

Copying, rather marking if I'm to be precise, is slightly different in the inspector.  So hope I got the right part out.

`<g class="ScatterPanel-7"><g transform="translate(563.7, 301) scale(1)"><text class="ScatterXTitleRect" alignment-baseline="hanging" text-anchor="middle" width="32.8" height="14" fill="white">RSRP</text></g><g transform="translate(0, 137.5) scale(1)"><text class="ScatterXTitleRect" text-anchor="left" width="57.39999999999999" height="14" fill="#777">latency</text></g><g transform="translate(0, 281)" fill="none" font-size="10" font-family="sans-serif" text-anchor="middle"><path class="domain" stroke="currentColor" d="M87.89999999999999,-261V0.5H1040.5V-261"></path><g class="tick" opacity="1" transform="translate(87.89999999999999,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">74.0</text></g><g class="tick" opacity="1" transform="translate(151.40666666666755,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">74.2</text></g><g class="tick" opacity="1" transform="translate(214.91333333333512,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">74.4</text></g><g class="tick" opacity="1" transform="translate(278.4199999999982,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">74.6</text></g><g class="tick" opacity="1" transform="translate(341.92666666666577,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">74.8</text></g><g class="tick" opacity="1" transform="translate(405.4333333333333,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">75.0</text></g><g class="tick" opacity="1" transform="translate(468.9400000000009,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">75.2</text></g><g class="tick" opacity="1" transform="translate(532.4466666666685,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">75.4</text></g><g class="tick" opacity="1" transform="translate(595.9533333333316,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">75.6</text></g><g class="tick" opacity="1" transform="translate(659.4599999999991,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">75.8</text></g><g class="tick" opacity="1" transform="translate(722.9666666666666,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">76.0</text></g><g class="tick" opacity="1" transform="translate(786.4733333333343,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">76.2</text></g><g class="tick" opacity="1" transform="translate(849.9800000000018,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">76.4</text></g><g class="tick" opacity="1" transform="translate(913.4866666666649,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">76.6</text></g><g class="tick" opacity="1" transform="translate(976.9933333333324,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">76.8</text></g><g class="tick" opacity="1" transform="translate(1040.5,0)"><line stroke="gray" y2="-261"></line><text fill="currentColor" y="3" dy="0.71em">77.0</text></g></g><g transform="translate(87.39999999999999, 0)" fill="none" font-size="10" font-family="sans-serif" text-anchor="end"><path class="domain" stroke="currentColor" d="M952.6,281.5H0.5V20.5H952.6"></path><g class="tick" opacity="1" transform="translate(0,267.1022820310239)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">22</text></g><g class="tick" opacity="1" transform="translate(0,249.8617428167789)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">24</text></g><g class="tick" opacity="1" transform="translate(0,232.6212036025339)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">26</text></g><g class="tick" opacity="1" transform="translate(0,215.38066438828895)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">28</text></g><g class="tick" opacity="1" transform="translate(0,198.140125174044)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">30</text></g><g class="tick" opacity="1" transform="translate(0,180.89958595979897)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">32</text></g><g class="tick" opacity="1" transform="translate(0,163.659046745554)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">34</text></g><g class="tick" opacity="1" transform="translate(0,146.41850753130902)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">36</text></g><g class="tick" opacity="1" transform="translate(0,129.17796831706403)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">38</text></g><g class="tick" opacity="1" transform="translate(0,111.93742910281907)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">40</text></g><g class="tick" opacity="1" transform="translate(0,94.69688988857408)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">42</text></g><g class="tick" opacity="1" transform="translate(0,77.45635067432909)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">44</text></g><g class="tick" opacity="1" transform="translate(0,60.215811460084126)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">46</text></g><g class="tick" opacity="1" transform="translate(0,42.975272245839136)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">48</text></g><g class="tick" opacity="1" transform="translate(0,25.734733031594175)"><line stroke="gray" x2="952.6"></line><text fill="currentColor" x="-3" dy="0.32em">50</text></g></g><defs><clipPath id="grid"><rect x="87.39999999999999" y="20" width="952.6" height="261"></rect></clipPath></defs><g><g clip-path="url(#grid)"></g></g><g>NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaN</g></g>
`

**Comment by eriktar** [comment]
I have found a way around my issue.  Having three separate searches, then letting grafana do the join. While solving the immediate graphing issue it creates a maintenance issue for me.  The search output should also be used for other outputs than grafana (another in house tool and gnuplot). 

![image](https://user-images.githubusercontent.com/5344481/120274720-89fca280-c2b0-11eb-806c-fa12ff2642a9.png)
