### ISSUE TITLE
Feature requests: change size of axis labels and threshold line

### ISSUE THREAD

**Issue by jeaninedata** [michaeldmoore/michaeldmoore-scatter-panel#13]
Hi, I am very happy with the scatter plot plug in, so thank you!

I have two feature requests:
1: I would like to be able to change the font size of the y and x axis labels, they are very small now. 
2: It would be nice if we can insert a threshold line in the plot (like it is possible now in the regular grafana graph panel). 

Thank you!

**Comment by michaeldmoore** [comment]
Added fontsize and color selection as of (next release 1.2.0)
