### ISSUE TITLE
[Feature] Logarithmical axes

### ISSUE THREAD

**Issue by GarryG** [michaeldmoore/michaeldmoore-scatter-panel#15]
After upgrading from Grafana 6.x to 8.x, I needed a replacement of plotly which sadly isn't working for 8.x.
It had the option to display either X or Y axis as a logarithmical scale ... any chance of adding this to Scatter?

**Comment by michaeldmoore** [comment]
I'll look into it when I get the chance.  Maybe not for a week or two.
