### ISSUE TITLE
Should this plugin work with Loki logs?

### ISSUE THREAD

**Issue by thundersen** [michaeldmoore/michaeldmoore-scatter-panel#16]
First of all a big thanks for this great plugin.

I have tried visualizing metrics parsed out of Loki log lines. Interestingly this seems to be the only visualization type that can put any fields that I parse out of log lines on the X axis. All the other visualizations can only deal with timestamps or Loki metrics queries which are also always time based.

But: the field definitions are randomly reset all the time, so it's not really useable.

Have you ever tried using it for Loki log lines? I feel that this would be a great unique feature that would make this plugin useful even after the introduction of the new XY Chart panel.

**Comment by michaeldmoore** [comment]
I don't know anything about Loki other than it exists and has something to
do with log files.

Give me a sample log file and walk me through the set-up and configuration
and I'll take a look.

No promises.

Michael Moore

**Comment by michaeldmoore** [comment]
Sorry, I forgot all about this.

Before I waste a lot of time though, can you check and see if you still have a problem?  Maybe (I 'm hoping) you have found a way to make it work without me doing anything....
