### ISSUE TITLE
Feature Request: Usage of Dashboard Variables in the Scatter Panel

### ISSUE THREAD

**Issue by frechdaex** [michaeldmoore/michaeldmoore-scatter-panel#18]
THX for the scatter panel.

I tried to build a very variable dashboard, were I can define the X and Y axis by a dashboard variable. 
It could look like this. Select a probe and a checkpoint and display the graph with the selected parameter X and Y.
![image](https://user-images.githubusercontent.com/25974764/141958618-09846604-ff7a-4438-8fa8-dc768d437e92.png)

The parameter X and Y is a list of possible evaluations. In my case page size, elements, number of requests and page size timings.  

The panel configuration need the possibility to use the dashboard variable and has to reload on a variable change.
![image](https://user-images.githubusercontent.com/25974764/141959255-e2207ef0-7865-47b0-88de-1648ca20f0b7.png)

Maybe this is also interesting and useful for others.
Eric

Edit:
The reload on a variable change is currently working. So it would be nice to set the selected parameter as axis title.

**Comment by michaeldmoore** [comment]
I think I understand, and I have a couple of ideas for you.

First.  Internally, the configuration settings are actually integers
(representing the column number in the table data set) - the text displayed
in the field selectors are the names of the field corresponding to these
integers.
So, if you create a scatter panel with X and Y defined as in your query,
internally this would set XAxisCol=0 and YAxisCol=1.  Changing the
selectors will automatically force a re-query (I think) and the scatter
panel will continue to show X and Y according to the columns 0 and 1.

That is to say - I think it should already work the way you want without me
having to make any changes.  Try it and see.


The second thought - especially if for some reason the first idea doesn't
do what you need - check out the new XYChart panel built into Grafana.  I
created Scatter to solve a problem I had and only later read that Grafana
had a similar panel in the works.  I think XYChart is available now as of
Grafana 8.x.x.  I haven't looked at it yet, but I expect it is altogether a
much more polished and useful panel - though most likely not as
configurable as my Scatter panel.  Anyway, I expect I'll be retiring the
Scatter panel sometime, assuming the XYChart lives up to its promise.
 Take a look and if neither of these ideas work out, let me know and I'll
see what I can do.

Regards,
Michael Moore

**Comment by frechdaex** [comment]
Thanks for the fast replay Michael.

I will try the XYChart. It is currently in the Alpha.
