### ISSUE TITLE
Can't set the label of axes for each graphs individually...

### ISSUE THREAD

**Issue by IDEYuichi** [michaeldmoore/michaeldmoore-scatter-panel#28]
Thank you very much for providing great plug-in!
Now we use it with grafana v.8.1.4. For example, when we put 3 panels of scatter plot, we can't set the labels individually, the name of all labels become same...
Is it an issue of grafana? or of your plug-in?
If there is the same post here, I'm sorry but I can't find...

Best regards,
Yuichi

**Comment by michaeldmoore** [comment]
Yes, this is a known problem - due, I'm convinced, to a long-standing bug
in Grafana itself.

I'm about to release an enhanced version of this plugin soon, but as of
this moment - the problem remains when there is more than one Scatter panel
on a single dashboard.

Grafana is releasing an official panel called XYChart (or something like
that), that I expect to replace Scatter.  I think you can already enable
the XYChart panel, though I haven't tried it yet myself.

Good luck
Michael Moore

**Comment by IDEYuichi** [comment]
Thank you very much, Michael

We'll try the XYChart panel.
And, of course, we'll expect the bug fix.

Best reagrd,
Yuichi
