### ISSUE TITLE
Link from grafana plugins site is broken

### ISSUE THREAD

**Issue by sirockin** [michaeldmoore/michaeldmoore-scatter-panel#3]
The Project Site link on [this page](https://grafana.com/grafana/plugins/michaeldmoore-scatter-panel/) points to:
https://github.com/michaedmoore/michaeldmoore-scatter-panel instead of https://github.com/michaeldmoore/michaeldmoore-scatter-panel

**Comment by michaeldmoore** [comment]
I'll fix this with the next update - coming (I expect) in the next week or so.
