### ISSUE TITLE
Nice to have: dynamic number of series based on value in column

### ISSUE THREAD

**Issue by zpostfacto** [michaeldmoore/michaeldmoore-scatter-panel#31]
Right now as far as I can tell, to use multiple series, each series must have its own column, e.g.:

```
Age   Boys  Girls
10    18    13
11    20    24
```

In my case, I don't know what the series are ahead of time, or even how many there are.  It would be nice if the series could be dynamically determined based on the value of a column:

```
Age   Gender   Number
10    Boy      18
10    Girl     13
11    Boy      20
11    Girl     24
```

**Comment by michaeldmoore** [comment]
Interesting idea, and not one I would have thought of myself.

At first thoughts, this seems like something too disruptive to consider,
but on reflection, maybe all it needs is a little grouping transformation
on the date - converting your format to the expected column per value
format.

Recent versions of Grafana include systems for transforming and
reconfiguring data sets already.  Mosty, these seem to be for
time-formatted data sets, not table formatted ones.  I've played around
with some of these but so far, haven't spent the time to be sure if these
can do what you want already and hence not require any program changes on
my side.

Before I do anything more on this idea, please take a good hard look at the
built-in data transformation capabilities built into Grafana - especially
concerning grouping (this is what you'd need to convert your Gender column
into girls and boys).

Good luck - and if you're convinced it can't be done - let me know and I'll
see if I can make a simple addition to the scatter panel to make it work.

Michael Moore
