### ISSUE TITLE
Dynamic axis setup

### ISSUE THREAD

**Issue by stephanritscher** [michaeldmoore/michaeldmoore-scatter-panel#34]
Hi,

I'm currently setting up a grafana + influx setup for monitoring power consumption and the scatter plugin fits perfectly for comparing the consumption of different timeshifts in one graph, e.g. compare the monthly consumption of different years.

Since grafana generally supports dynamic ranges, supporting this in the scatter plugin would translate into a dynamic axis setup.

To make this more clear, I currently use the following query:
```
import "date"
import "strings"

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart), stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "power-consumption")
  |> aggregateWindow(every: 1mo, createEmpty: true, fn: sum, timeSrc: "_start")
  |> map(fn: (r) => ({
      year: date.year(t: r._time),
      month: date.month(t: r._time),
      _value: r._value,
    }))
  |> pivot(rowKey: ["month"], columnKey: ["year"], valueColumn: "_value")
  |> sort(columns: ["month"])
```
Assuming you have a measurement called "power-consumption", this query aggregates monthly sum of the power-consumption and then outputs a table like:
```
|month|2020|2021|2022|
|    1| 100| 120| 130|
|    2|  60|  70|  80|
|    3|  50|  60|    |
|    4|  40|  50|    |
|    5|  30|  35|    |
|    6|  25|  30|    |
|    7|  20|  20|    |
|    8|  20|  25|    |
|    9|  35|  40|    |
|   10|  55|  60|    |
|   11|  60|  70|    |
|   12|  80|  90|    |
```
This is drawn by the scatter plugin, as intended, with the month on the x-axis and the years on the y-axis.
Since, depending on the time range, I might have different years and even different amount of years in the output table, I would like to avoid manually selecting the y-axes which shall be drawn. Instead there should be an option to draw all y-axes except the one used for labelling the x-axis.
It would be more advanced to allow a filtering of the columns to be drawn based on the column name (e.g. using regular expressions), but that could also be handled by the query design in my opinion.

Also, I wonder, if the pivot I use in this kind of query might be have an performance hit for larger queries which could be avoided in one way or the other.

**Comment by michaeldmoore** [comment]
Not completely sure what you are asking for here.  In case you missed it
though, note that you can choose as many Y-axis plots as you want (though
you can't adjust the number of these columns dynamically, and maybe that's
what you are asking for).  Also, note that the scaling does adjust
automatically unless overridden by setting the extents manually.  But I
expect you can see that already.

As to the efficiency of the query - that's out of my hands.  I'm just
impressed that you could get it working - well done.  I don't think I could
have worked this out. :)

**Comment by stephanritscher** [comment]
Hi and thanks for the fast response.

As you suggested, I already did configure multiple fixed y-axis plots. I didn't fumble with scaling, so yes, that works out of the box / dynamically which is awesome.

My request would be to have an automatic selection which y-axes to plot.
What you would need for a start in my opinion:
* A placeholders notation in the Field box (or most simply a way to select all columns not used for the x-axis labels)
* The color should be selected automatically, ideally with "nice" colors which are easily to distinguish (similar logic as a time series widget displaying a graph with multiple _field's)
* Other options like point size, line size, interpolation type can be left on default or changed for all graphs at once (in the advanced version with placeholders you could add multiple sections with placeholders if you need different settings)

PS: I wasn't thinking that the query was overly complex (I left out some of the fiddly details like locale and precomputation from a counter via interpolation and derivation in my post ;-)), but I'm kind of used to SQL which often is less readable. My first approaches using time series graph instead of the scatter plugin for the same were much worse.

**Comment by michaeldmoore** [comment]
I think this should work the way you describe out of the box.  Try making a new panel and see if it correctly sets the defaults.
