### ISSUE TITLE
Suggestion for new changes

### ISSUE THREAD

**Issue by Casper-RV** [michaeldmoore/michaeldmoore-scatter-panel#39]
Hello! Thank you for making this plug-in. Pretty sweet!   I hope to see something (hopefully) simple to add. I would like to add lines myself (vertical or horizontal) to my scatter plot. Lines such as this.

![redLine](https://user-images.githubusercontent.com/103562025/202458587-537d5a24-6b75-48f2-8bf4-4ac63e5b744f.PNG)

(If you cannot see the picture, it is essentially a red vertical line in the middle of the dashboard)

**Comment by michaeldmoore** [comment]
Added in the soon-to-be-released version 1.2.0
