### ISSUE TITLE
Feature request: data from two separate series

### ISSUE THREAD

**Issue by sirockin** [michaeldmoore/michaeldmoore-scatter-panel#4]
Nice plugin, thanks!

I'd like to try using it with my InfluxDB data set in which values are organised in a single measurement distinguished by a 'topic' tag name. It's difficult (impossible?) to extract two columns of data using a single query. It would be great if I could provide the X and Y values from two separate queries.

Cheers

**Comment by sirockin** [comment]
Some further information: My X and Y values would look like this:
```
SELECT median("value") AS "foo" FROM "channels" WHERE ("topic" = 'foo') AND $timeFilter GROUP BY time($__interval) fill(previous)
```
and 
```
SELECT median("value") AS "bar" FROM "channels" WHERE ("topic" = 'bar') AND $timeFilter GROUP BY time($__interval) fill(previous)
```
While it is possible to combine these into a single query by simply separating the two statements with a semicolon, the resulting data is two separate series concatenated to each other, rather than a series with two value columns.

**Comment by michaeldmoore** [comment]
I'll think about this, but it seems a bit weird as with two
separate queries, there might be a different number of data points, or the
two queries might have different sort order etc (probably not a
problem with InFlux)

I've only just started playing with influx and the query language takes a
bit of getting used to.  I'll think about this and let you know what i come
up with.

Thank BTW for finding the typo in the listing - I expect this is my sloppy
typing (you'd think I could spell my own name though).  Now to figure out
how to get Grafana to fix it for me... :(

**Comment by thomasbromkapsdata** [comment]
@sirockin 
I found a solution with influxdb: it is to use the "transform" "outer join by time", but it is not really convenient and every field have the name "value", but in the queries order.
And I suppose you still should pay attention the is issues of number of data point, but as Michael said and you know probably it is not a big deal with Influx.
Maybe michael can put that in the tutorial as influx is widely used.
