### ISSUE TITLE
Cannot Install using commandline options

### ISSUE THREAD

**Issue by jcocampo** [michaeldmoore/michaeldmoore-scatter-panel#5]
executing locally this commandline --> `grafana-cli plugins install michaeldmoore-scatter-panel`

gives me the error below:

`Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error`

**Comment by michaeldmoore** [comment]
I can't reproduce this - it seems to be working properly.  Maybe you didn't have internet connectivity or something when you ran this.

Can you try again and if the problem persists, send some details regarding the environment you are trying to work with (OS, versions etc etc.)?

If under linux, make sure you ran sudo apt install update & upgrade recently.
