### ISSUE TITLE
NULL displayed as value 0 instead of no value

### ISSUE THREAD

**Issue by RobAtticus** [michaeldmoore/michaeldmoore-scatter-panel#8]
I have two data series LEFT JOINed in a Postgres database where one has more y-values than the second, so the second series has several NULL values at the end. This panel currently displays them as having value 0, where having them be missing would be preferred (or at least an option to toggle the behavior)

**Comment by michaeldmoore** [comment]
Good catch.

I have a fix for this in the upcoming release.
