### ISSUE TITLE
y-axis labels cut off when more than 5 digits

### ISSUE THREAD

**Issue by RobAtticus** [michaeldmoore/michaeldmoore-scatter-panel#9]
See attachment
<img width="80" alt="Screen Shot 2021-04-15 at 10 34 52 PM" src="https://user-images.githubusercontent.com/1501309/114963494-e60f8280-9e3a-11eb-8b91-0de3ff6b233c.png">

**Comment by michaeldmoore** [comment]
Good catch.

I have a fix for this in the upcoming release.

**Comment by michaeldmoore** [comment]
Fixed (I think)
